<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-P8GMCAP" failures="2" tests="8" name="Test" time="0.278" errors="0" timestamp="2022-11-18T12:53:11 IST">
  <testcase classname="org.testng.RetryAnalyser_Concept" name="password" time="0.029">
    <skipped/>
  </testcase> <!-- password -->
  <testcase classname="org.testng.RetryAnalyser_Concept" name="password" time="0.002">
    <skipped/>
  </testcase> <!-- password -->
  <testcase classname="org.testng.RetryAnalyser_Concept" name="password" time="0.006">
    <skipped/>
  </testcase> <!-- password -->
  <testcase classname="org.testng.RetryAnalyser_Concept" name="password" time="0.006">
    <failure type="java.lang.AssertionError" message="expected [Ashokan4#] but found [Asokan4#]">
      <![CDATA[java.lang.AssertionError: expected [Ashokan4#] but found [Asokan4#]
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- password -->
  <testcase classname="org.testng.RetryAnalyser_Concept" name="userName" time="0.005">
    <skipped/>
  </testcase> <!-- userName -->
  <testcase classname="org.testng.RetryAnalyser_Concept" name="userName" time="0.04">
    <skipped/>
  </testcase> <!-- userName -->
  <testcase classname="org.testng.RetryAnalyser_Concept" name="userName" time="0.002">
    <skipped/>
  </testcase> <!-- userName -->
  <testcase classname="org.testng.RetryAnalyser_Concept" name="userName" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [Guru Prasath A] but found [ Guru Prasath A]">
      <![CDATA[java.lang.AssertionError: expected [Guru Prasath A] but found [ Guru Prasath A]
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- userName -->
</testsuite> <!-- Test -->
